### ISSUE TITLE
the first dependencies log shows nothing

### ISSUE THREAD

**Issue by pegurnee** [power-cosmic/requirator#2]
looking and the console we get:

```
hello world
basicModule: basic module
equation: 81
This doesn' use define or require. It's just console.logging
```

'with dependencies' should show up before equation.

**Comment by tyler-hoffman** [comment]
Yeah, I missed that. Looks like it has to do with plain.js not defining a module.

**Comment by tyler-hoffman** [comment]
It should be taken care of now, but double check me. The message shows up later than expected, but that's probably just due to how events are put in the queue.
